#!/bin/bash -e

#CURRENT=`git describe --tags --abbrev=0`
CURRENT=`git rev-list --all | wc -l`
NEW=`echo $CURRENT + 1 | bc`

COMMIT="[$NEW]"

if [[ ! -z $@ ]]; then COMMIT="$@"; fi

git add . --all
git commit -m "${COMMIT}"
git tag ${NEW}
