#!/bin/bash
cd ~/.config/i3/
echo "init stage2"
type make >/dev/null || sudo apt-get install make -qy || true
type make >/dev/null || sudo dnf install make -qy || true
echo "make... in path ${PWD}"
sleep 2
echo "."
sleep 2
echo "."
sleep 2
echo "."
sleep 2
echo "."
make -n