#!/bin/bash
#
# curl https://raw.githubusercontent.com/skroes/i3-config/master/init | bash
# or
# wget https://raw.githubusercontent.com/skroes/i3-config/master/init -O - | bash
# 
set -e
cd ~
type git || sudo apt-get install git -y || true
type git || sudo dnf install git -y || true
test -d ~/.config || mkdir ~/.config
git clone https://github.com/skroes/i3-config.git ~/.config/i3
exec ~/.config/i3/initstage2
#
