#!/bin/bash

# packages
#if [ ! `dpkg -l | grep -w 'i3-wm' | wc -l` -eq 0 ]; then
#  echo "already installed"
#  exit 1
#fi

# sudo ln ~skroes/.i3/files/usr/share/xsessions/gnome-i3.desktop /usr/share/xsessions/gnome-i3.desktop 
# sudo ln ~skroes/.i3/files/usr/share/gnome-session/sessions/i3.session /usr/share/gnome-session/sessions/i3.session


# ubuntu 1404
sudo apt-get update
sudo apt-get install dmenu i3-wm gnome-settings-daemon unclutter gnome-tweak-tool gnome-session

# optional i3status

# https://faq.i3wm.org/question/1/how-can-i-get-rid-of-the-nautilus-desktop-window/
gsettings set org.gnome.desktop.background show-desktop-icons false
gconftool-2 \
--type bool \
--set /apps/nautilus/preferences/show_desktop false

sudo apt-get install python-pip -y
sudo pip install i3-py

mkdir ~/git/personal -p
cd ~/git/personal

