version: "3.7"

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: [ "redis-server", "/etc/redis.conf" ]
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis.conf
      - ./redis-acl.conf:/etc/redis-acl.conf

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=kroescontrol
      - HTTP_PASSWORD=SuperSecret
    ports:
      - 8083:8081
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  default:
    external:
      name: grafana-tutorial-environment_grafana
